services:
  master-bot:
    build: .
    depends_on:
      lavalink:
        condition: service_healthy
    links:
      - lavalink
  lavalink:
    image: fredboat/lavalink:dev
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    healthcheck:
      test: 'echo lavalink'
